### ISSUE TITLE
[Error] IndexError: list index out of range with crackserver.py

### ISSUE THREAD

**Issue by s7x** [arisada/malifar#2]
Hello,

When running the crackserver and launching the dumper, we encounter the following error:

```log
$ malifar-crackserver 

Listening...
New client
New client
Params b''
Exception: list index out of range
Traceback (most recent call last):
  File "/usr/share/malifar/crackserver.py", line 78, in handle_solver
    nsec3params = NSEC3Params.from_serial(params)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/malifar/nsec3hash.py", line 53, in from_serial
    params[0]=int(params[0])
                  ~~~~~~^^^
IndexError: list index out of range
Params b''
Exception: list index out of range
Traceback (most recent call last):
  File "/usr/share/malifar/crackserver.py", line 78, in handle_solver
    nsec3params = NSEC3Params.from_serial(params)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/malifar/nsec3hash.py", line 53, in from_serial
    params[0]=int(params[0])
                  ~~~~~~^^^
IndexError: list index out of range
```

### Commands Used

```bash
# In a terminal
crackserver.py

# In a second terminal
dumper.py io
```

**Comment by fishilico** [comment]
Hello,
I am using malifar and while looking at the issues, I stumbled upon this one. I matches exactly an issue I encountered and solved. I am sharing what I understood and what I did to solve it, in case it helps you (or other people stumbling upon the same issue).

When `solver.py` connects to `crackserver.py`, it starts by sending the NSEC3 parameters of the DNS zone: https://github.com/arisada/malifar/blob/165e7dd51c0bf80ceca81647fa18dbc66005784e/dumper.py#L440-L450

... but in my case, the parameters were never sent and the connection was closed. This is why `crackserver.py` was receiving an empty line (and logged `Params b''`) and failed decoding the NSEC3 parameters.
The reason why the parameters were never sent is that an exception was raised by `await asyncio.open_connection(host, port)`. This exception was [`asyncio.CancelledError`](https://docs.python.org/3/library/asyncio-exceptions.html#asyncio.CancelledError), which was not a subtype of `Exception` so the coroutine just stopped without logging anything. Why was the coroutine cancelled? Because another one was raising an uncaught `OSError` while attempting to connect to a nameserver over IPv6. And the scanner coroutine does not catch `OSError` in https://github.com/arisada/malifar/blob/165e7dd51c0bf80ceca81647fa18dbc66005784e/fastdns.py#L164-L169

To fix this issue, several possibilities are possible:

- Run malifar from a system which has both IPv4 and IPv6.
- Specify the IPv4 addresses of the nameservers to use, so that IPv6 ones are not attempted.
- Modify the code to make it more robust:
  - Catch `OSError` in `scanner_coroutine` (such as https://github.com/fishilico/malifar/commit/23bc0e141cd16503cf0ce4a9a3a5651c438b7e1e).
  - Make `crackserver.py` detect empty NSEC3 parameters and display a nice error message stating the client closed the connection early.
  - Add a command-line parameter to only use IPv4 nameservers (such as https://github.com/fishilico/malifar/commit/c3fdb06cf6005294e97c70324ae04a8d1621c400).

That being said, I don't know if the issue you encountered was the same one as mine. It would be useful to have more context (did the host have both IPv4 and IPv6 addresses? Was `dumper.py` displaying anything?)

[N.B. I am open to create Pull Requests with the commits I mentioned, if this project is still maintained]
